defmodule Defdo.Tenant.Worker do
  @moduledoc """
  Tenant-safe Oban worker behaviour — part of the Tenant Boundary Kit.

  Replace `use Oban.Worker` with `use Defdo.Tenant.Worker` for automatic
  tenant-context restoration before every job execution.

  ## Usage

      defmodule MyApp.Workers.SyncTenant do
        use Defdo.Tenant.Worker, queue: :default, max_attempts: 3

        def perform_with_tenant(%Oban.Job{args: args}) do
          # tenant context is already restored — Repo queries are scoped
          do_tenant_work(args)
        end
      end

  ## How it works

  1. `perform/1` is generated by the macro and calls your `perform_with_tenant/1`
     after restoring tenant context from the job's `meta["defdo_tenant_context"]`.
  2. After `perform_with_tenant/1` returns (even on exception), context is cleared.
  3. `Defdo.Tenant.Worker.restore_context_from_job/1` emits telemetry on restore/missing.
  4. Missing context follows `Defdo.Tenant.Config` enforcement (warn/raise).
  5. Job insertion via `Defdo.Tenant.Oban.new/2` or `Defdo.Tenant.Oban.insert/2`
     automatically attaches context to `meta`.

  ## Telemetry

  | Event | Metadata |
  |---|---|
  | `[:defdo, :tenant, :context, :restored]` | `boundary: :oban`, `worker`, `scope` |
  | `[:defdo, :tenant, :context, :missing]` | `boundary: :oban`, `worker` |
  """

  alias Defdo.Tenant.Config
  alias Defdo.Tenant.Context

  @context_meta_key "defdo_tenant_context"

  defmacro __using__(opts) do
    quote do
      use Oban.Worker, unquote(opts)

      @impl true
      def perform(job) do
        Defdo.Tenant.Worker.restore_context_from_job(job)
        perform_with_tenant(job)
      rescue
        e -> reraise e, __STACKTRACE__
      after
        Defdo.Tenant.Context.clear()
      end

      defoverridable perform: 1

      def perform_with_tenant(_job), do: :ok
      defoverridable perform_with_tenant: 1
    end
  end

  @doc """
  Restore tenant context from an Oban job's `meta` map.

  Called automatically by the generated `perform/1`. Also available as a
  standalone helper when wrapping existing workers without the macro.

  Returns the restored `%Defdo.Tenant.Context{}` or `nil`.
  """
  @spec restore_context_from_job(Oban.Job.t()) :: Context.t() | nil
  def restore_context_from_job(%Oban.Job{meta: meta, worker: worker}) do
    Context.clear()

    case Map.get(meta, @context_meta_key) do
      map when is_map(map) and map_size(map) > 0 ->
        ctx = Context.from_serializable(map)
        Context.put(ctx)

        :telemetry.execute(
          [:defdo, :tenant, :context, :restored],
          %{count: 1},
          %{boundary: :oban, worker: worker, scope: ctx.scope}
        )

        ctx

      _ ->
        :telemetry.execute(
          [:defdo, :tenant, :context, :missing],
          %{count: 1},
          %{boundary: :oban, worker: worker}
        )

        cond do
          Config.raising?() ->
            raise ArgumentError,
                  "Oban job #{inspect(worker)} has no tenant context in meta. " <>
                    "Use Defdo.Tenant.Oban.new/2 or Defdo.Tenant.Oban.insert/2 to attach context."

          Config.warning?() ->
            require Logger
            Logger.warning("Oban job #{inspect(worker)} has no tenant context in meta")

          true ->
            :ok
        end

        nil
    end
  end
end
